### ISSUE TITLE
Toon 1 resolution

### ISSUE THREAD

**Issue by arcidodo** [oepi-loepi/doorcam-HADOM#3]
On the configuration screen is not everything visible, please add an scrollbar :-) 

![image](https://user-images.githubusercontent.com/678514/92730035-80728980-f373-11ea-8ca5-e58b795e188a.png)

**Comment by oepi-loepi** [comment]
Yes, you are right. I tested on Toon 2 which has another resolution (and is also much faster). I will crop a bit so it will fit the Toon 1. ( think it needs to be cropped by 40 in total

**Comment by arcidodo** [comment]
yea, the toon 2 is allot faster.. im searching for one on MP ;-)

**Comment by oepi-loepi** [comment]
Ja ok ze staan soms op mpl voor weinig (soms zelfs voor 50 euro). Rooten zal alleen kunnen door een van de specialisten. TheHog of door TerrorSource. Zij geven niet vrij hoe ze dat doen.

Groet, rob


Verstuurd vanaf mijn iPad

**Comment by oepi-loepi** [comment]
Ik heb zojuist gehoord dat je nu een toon 2 hebt. TOP!

Groet, Rob

Verstuurd vanaf mijn iPad

**Comment by arcidodo** [comment]
haha :-p nieuws gaat snel! krijg hem als het goed is aankomende dinsdag binnen ;-)

**Comment by oepi-loepi** [comment]
Ja klopt, nieuws gaat snel. Heb je al wat kunnen doen aan de handleiding of heb je hulp nodig? Ik wil eigenlijk niet de nieuwe versie plaatsen zonder een duidelijke handleiding omdat ik zelf geen vragen over ha kan beantwoorden.

Groet, rob

Verstuurd vanaf mijn iPad
